---
- name: get IAM token
  uri:
    url: "https://iam.cloud.ibm.com/identity/token"
    method: POST
    body_format: form-urlencoded
    body: "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey={{ ibmcloud_api_key }}"
  register: iam_token

- name: update redirect_uris
  uri:
    url: "{{ appid_mgmt_url }}/config/redirect_uris"
    method: PUT
    headers:
      Authorization: "Bearer {{ iam_token.json|json_query('access_token') }}"
      accept: "application/json"
    body_format: json
    return_content: yes
    status_code: [200, 204]
    body: '{"redirectUris": ["https://{{ cluster_hostname }}/authservice/oidc/callback"]}'

- name: upload kubeflow logo
  shell: |
    curl -X 'POST' \
    '{{ appid_mgmt_url }}/config/ui/media?mediaType=logo' \
    -H 'accept: application/json' \
    -H 'Authorization: Bearer {{ iam_token.json|json_query('access_token') }}' \
    -H 'Content-Type: multipart/form-data' \
    -F 'file=@{{ lookup('env', 'HOME') }}/bin/kubeflow-logo.png;type=image/png'


- name: create user
  uri:
    url: "{{ appid_mgmt_url }}/cloud_directory/Users"
    method: POST
    headers:
      Authorization: "Bearer {{ iam_token.json|json_query('access_token') }}"
      accept: "application/json"
    body_format: json
    return_content: yes
    status_code: [200, 201, 204, 409]
    body: '{ "emails": [ { "value": "{{ appid_username }}", "primary": true } ], "userName": "{{ appid_username }}", "password": "{{ appid_password }}", "status": "CONFIRMED" }'

- name: disable facebook
  uri:
    url: "{{ appid_mgmt_url }}/config/idps/facebook"
    method: PUT
    headers:
      Authorization: "Bearer {{ iam_token.json|json_query('access_token') }}"
      accept: "application/json"
    body_format: json
    return_content: yes
    status_code: [200, 204]
    body: '{ "isActive": false }'

- name: disable google
  uri:
    url: "{{ appid_mgmt_url }}/config/idps/google"
    method: PUT
    headers:
      Authorization: "Bearer {{ iam_token.json|json_query('access_token') }}"
      accept: "application/json"
    body_format: json
    return_content: yes
    status_code: [200, 204]
    body: '{ "isActive": false }'

- name: disable cloud directory
  uri:
    url: "{{ appid_mgmt_url }}/config/idps/cloud_directory"
    method: PUT
    headers:
      Authorization: "Bearer {{ iam_token.json|json_query('access_token') }}"
      accept: "application/json"
    body_format: json
    return_content: yes
    status_code: [200, 204]
    body: '{"isActive":true,"config":{"selfServiceEnabled":true,"interactions":{"identityConfirmation":{"accessMode":"FULL","methods":["email"]},"welcomeEnabled":true,"resetPasswordEnabled":true,"resetPasswordNotificationEnable":true},"signupEnabled":false}}'

- name: restart oauth-service
  shell: |
    KUBECONFIG={{ kube_config }} {{ lookup('env', 'HOME') }}/bin/kubectl rollout restart sts authservice -n istio-system