---
- name: create load balancer for istio-ingressgatewway
  shell: |
    ibmcloud config --check-version=false
    KUBECONFIG={{ kube_config }} {{ lookup('env', 'HOME') }}/bin/kubectl get svc/istio-ingressgateway -n istio-system -o json \
    | {{ lookup('env', 'HOME') }}/bin/jq '.spec.type="LoadBalancer"' | KUBECONFIG={{ kube_config }} {{ lookup('env', 'HOME') }}/bin/kubectl apply -f - || true

    # wait for lb
    while true; do
      ingress_hostname=$(KUBECONFIG={{ kube_config }} {{ lookup('env', 'HOME') }}/bin/kubectl get svc/istio-ingressgateway -n istio-system -o json | {{ lookup('env', 'HOME') }}/bin/jq -r '.status.loadBalancer.ingress[0].hostname')
      if [[ -z "$ingress_hostname" || "$ingress_hostname" = "null" ]]; then
        sleep 20
        continue
      fi
      break
    done

    ibmcloud ks nlb-dns replace -c "{{ cluster_name }}" --nlb-subdomain "{{ cluster_hostname }}" --lb-host "$ingress_hostname"
