---
- name: create kfdef
  file:
    path: "{{ lookup('env', 'HOME') }}/kfdef"
    state: directory
    mode: '0777'

- name: download kfdef
  get_url:
    url: "{{ kfdef_uri }}"
    dest: "{{ lookup('env', 'HOME') }}/kfdef/kdef.yaml"
    mode: '0777'

- name: deploy kubeflow
  args:
    chdir: "{{ lookup('env', 'HOME') }}/kfdef"
  shell: |
    KUBECONFIG={{ kube_config }} {{ lookup('env', 'HOME') }}/bin/kubectl delete service istio-ingressgateway -n istio-system || true
    KUBECONFIG={{ kube_config }} {{ lookup('env', 'HOME') }}/bin/kfctl apply -f kdef.yaml
