---
- name: param env
  args:
    chdir: "{{ lookup('env', 'HOME') }}/manifests-1.6-branch"
  shell: |
    param=$(cat << EOF
    OIDC_PROVIDER={{ appid_oauthServerUrl }}
    REDIRECT_URL=https://{{ cluster_hostname }}/login/oidc
    OIDC_AUTH_URL={{ appid_oauthServerUrl }}/authorization
    EOF
    )
    secrets=$(cat << EOF
    CLIENT_SECRET={{ appid_secret }}
    CLIENT_ID={{ appid_clientId }}
    EOF
    )
    echo "$param" > dist/stacks/ibm/application/oidc-authservice-appid/params.env
    echo "$secrets" > dist/stacks/ibm/application/oidc-authservice-appid/secret_params.env

- name: deploy kubeflow
  args:
    chdir: "{{ lookup('env', 'HOME') }}/manifests-1.6-branch"
  shell: |
    {{ lookup('env', 'HOME') }}/bin/kustomize build iks-multi \
      | KUBECONFIG={{ kube_config }} {{ lookup('env', 'HOME') }}/bin/kubectl apply -f -
    sleep 30
    {{ lookup('env', 'HOME') }}/bin/kustomize build iks-multi \
      | KUBECONFIG={{ kube_config }} {{ lookup('env', 'HOME') }}/bin/kubectl apply -f -
