---
- name: login IBM Cloud
  shell:
    cmd: ibmcloud login --apikey "{{ ibmcloud_api_key }}" --no-region

- name: set target
  shell:
    cmd: ibmcloud target -r "{{ region }}" -o "{{ org }}" -s "{{ space }}" -g "{{ resource_group }}"

- name: create bin
  file:
    path: "{{ lookup('env', 'HOME') }}/bin"
    state: directory
    mode: '0755'

- name: download 
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_ver }}/bin/linux/amd64/kubectl
    dest: "{{ lookup('env', 'HOME') }}/bin/kubectl"
    mode: '0555'

- name: get kube config
  shell:
    cmd: ibmcloud ks cluster config -c "yhwang-iks1.8"

- name: get namespace
  shell:
    cmd: "{{ lookup('env', 'HOME') }}/bin/kubectl get ns"

- name: get IAM token
  uri:
    url: "https://iam.cloud.ibm.com/identity/token"
    method: POST
    body_format: form-urlencoded
    body: "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey={{ ibmcloud_api_key }}"
  register: iam_token

- name: update redirect_uris
  uri:
    url: "{{ appid_mgmt_url }}/config/redirect_uris"
    method: PUT
    headers:
      Authorization: "Bearer {{ iam_token.json|json_query('access_token') }}"
      accept: "application/json"
    body_format: json
    return_content: yes
    status_code: [ 200, 204 ]
    body: "{\"redirectUris\": [\"{{ callback_uri }}\"]}"